// Each helper returns { raw, url } where:
//   raw  = raw.githubusercontent.com URL (fetch the HTML from here)
//   url  = github.io URL  (used as <base href> so relative assets resolve)

const UGS = n => ({
  raw:  `https://raw.githubusercontent.com/bubbls/UGS-Assets/main/${encodeURIComponent(n)}/index.html`,
  url:  `https://bubbls.github.io/UGS-Assets/${encodeURIComponent(n)}/`
});

const NG = n => ({
  raw:  `https://raw.githubusercontent.com/Neruvy/neruvy-games/main/games/${n}/index.html`,
  url:  `https://neruvy.github.io/neruvy-games/games/${n}/`
});

const NP = n => ({
  raw:  `https://raw.githubusercontent.com/Neruvy/web-port/main/${n}/index.html`,
  url:  `https://neruvy.github.io/web-port/${n}/`
});

const GP = n => ({
  raw:  `https://raw.githubusercontent.com/genizy/web-port/main/${n}/index.html`,
  url:  `https://genizy.github.io/web-port/${n}/`
});

const MT = n => ({
  raw:  `https://raw.githubusercontent.com/mathtut0r1ng/mathtut0r1ng.github.io/main/gamespage/games/${n}/index.html`,
  url:  `https://mathtut0r1ng.github.io/gamespage/games/${n}/`
});

const GAMES = [

  // ── UGS-ASSETS (bubbls/UGS-Assets) ───────────────────────────────────────
  { name: "1 Date Danger",             ...UGS("1-date-danger"),                            cat: "horror"      },
  { name: "10 Minutes Till Dawn",      ...UGS("10minutestilldawn"),                        cat: "shooter"     },
  { name: "2 Minute Football",         ...UGS("2 minute football"),                        cat: "sports"      },
  { name: "2-3-4 Player Games",        ...UGS("2-3-4-player-game"),                        cat: "multiplayer" },
  { name: "2 DOOM",                    ...UGS("2doom"),                                    cat: "action"      },
  { name: "3Dash",                     ...UGS("3dash"),                                    cat: "platformer"  },
  { name: "5B",                        ...UGS("5b"),                                       cat: "other"       },
  { name: "Antimatter Dimensions",     ...UGS("Antimatter Dimensions"),                    cat: "idle"        },
  { name: "Bumper Cars Soccer",        ...UGS("BUMPER CARS SOCCER"),                       cat: "sports"      },
  { name: "Blightborne",               ...UGS("Blightborne"),                              cat: "rpg"         },
  { name: "Burrito Bison",             ...UGS("BurritoBison-main"),                        cat: "action"      },
  { name: "Endacopia",                 ...UGS("Endacopia"),                                cat: "horror"      },
  { name: "Five Nights at Wario's",    ...UGS("FNAW-main"),                                cat: "horror"      },
  { name: "Five Nights at Osaka's",    ...UGS("Five Nights at Osaka's"),                   cat: "horror"      },
  { name: "Insomniary",                ...UGS("Insomniary"),                               cat: "horror"      },
  { name: "Stickman GTA",              ...UGS("STICKMAN GTA"),                             cat: "action"      },
  { name: "Stickman Clash",            ...UGS("Stickman Clash"),                           cat: "action"      },
  { name: "A Day in the Office",       ...UGS("a day in the office"),                      cat: "other"       },
  { name: "Adventure Capitalist",      ...UGS("adventure-capitalist"),                     cat: "idle"        },
  { name: "Ages of Conflict",          ...UGS("ages of conflict"),                         cat: "strategy"    },
  { name: "Airline Tycoon Idle",       ...UGS("airline-tycoon-idle"),                      cat: "idle"        },
  { name: "Alien Sky Invasion",        ...UGS("alien sky invasion"),                       cat: "shooter"     },
  { name: "Amazing Rope Police",       ...UGS("amazing-strange-rope-police-vice-spider"),  cat: "action"      },
  { name: "Amidst the Sky",            ...UGS("amidst the sky"),                           cat: "platformer"  },
  { name: "Angry Birds",               ...UGS("angry-bird"),                               cat: "puzzle"      },
  { name: "Apes vs Helium",            ...UGS("apesvshelium"),                             cat: "action"      },
  { name: "Arcade Volley",             ...UGS("arcade-volley"),                            cat: "sports"      },
  { name: "Archesspalago",             ...UGS("archesspalago"),                            cat: "puzzle"      },
  { name: "Astro Survivors",           ...UGS("astro survivors"),                          cat: "shooter"     },
  { name: "Aviamaster",                ...UGS("aviamaster"),                               cat: "strategy"    },
  { name: "Babel Tower",               ...UGS("babel tower"),                              cat: "puzzle"      },
  { name: "Backrooms 2D",              ...UGS("backrooms 2D"),                             cat: "horror"      },
  { name: "Bacon May Die",             ...UGS("bacon may die"),                            cat: "action"      },
  { name: "Bad Parenting",             ...UGS("bad-parenting"),                            cat: "platformer"  },
  { name: "Baldi's Basics",            ...UGS("baldis-basics"),                            cat: "horror"      },
  { name: "Baldi's Decomp",            ...UGS("baldi decomp"),                             cat: "horror"      },
  { name: "Ballistic",                 ...UGS("ballistic"),                                cat: "shooter"     },
  { name: "Banana Poker",              ...UGS("banana poker"),                             cat: "other"       },
  { name: "Barry Has a Secret",        ...UGS("barry has a secret"),                       cat: "horror"      },
  { name: "Baseball Bros",             ...UGS("baseball bros"),                            cat: "sports"      },
  { name: "Basket Stars",              ...UGS("basket stars"),                             cat: "sports"      },
  { name: "Basketball Superstars",     ...UGS("basketball-superstars"),                    cat: "sports"      },
  { name: "Beach Boxing Sim",          ...UGS("beach-boxing-sim"),                         cat: "sports"      },
  { name: "Bearsus",                   ...UGS("bearsus"),                                  cat: "action"      },
  { name: "Ben 10 Super Slammer",      ...UGS("ben 10 super slammer"),                     cat: "action"      },
  { name: "BFNSU",                     ...UGS("bfnsu"),                                    cat: "horror"      },
  { name: "Big 2048",                  ...UGS("big 2048"),                                 cat: "puzzle"      },
  { name: "Big Flappy Tower",          ...UGS("big flappy tower"),                         cat: "platformer"  },
  { name: "Block Miner",               ...UGS("block-miner"),                              cat: "idle"        },
  { name: "BlockPost",                 ...UGS("blockpost"),                                cat: "shooter"     },
  { name: "Blumgi Racers",             ...UGS("blumgi racers"),                            cat: "racing"      },
  { name: "Blumgi Rocket",             ...UGS("blumgi-rocket"),                            cat: "racing"      },
  { name: "Bounce Back",               ...UGS("bounce back"),                              cat: "puzzle"      },
  { name: "Bouncy Basketball",         ...UGS("bouncy basketball"),                        cat: "sports"      },
  { name: "Bouncy Motors",             ...UGS("bouncy motors"),                            cat: "racing"      },
  { name: "Bounty of One",             ...UGS("bounty of one"),                            cat: "rpg"         },
  { name: "Brawl 3D",                  ...UGS("brawl-3d"),                                 cat: "multiplayer" },
  { name: "Bullet Force",              ...UGS("bullet-force-multiplayer"),                 cat: "shooter"     },
  { name: "Capybara Clicker",          ...UGS("capybara clicker"),                         cat: "idle"        },
  { name: "Cat Mario",                 ...UGS("cat mario"),                                cat: "platformer"  },
  { name: "Cats Love Cake 2",          ...UGS("cats love cake 2"),                         cat: "puzzle"      },
  { name: "Cave Chaos 2",              ...UGS("cave chaos 2"),                             cat: "platformer"  },
  { name: "Cheese Chompers 3",         ...UGS("cheese chompers 3"),                        cat: "action"      },
  { name: "Chicken Gun",               ...UGS("chicken-gun"),                              cat: "shooter"     },
  { name: "Choppy Orc",                ...UGS("choppy orc"),                               cat: "platformer"  },
  { name: "CircloO 2",                 ...UGS("circlo02"),                                 cat: "puzzle"      },
  { name: "Clash of Vikings",          ...UGS("clashofvikings"),                           cat: "strategy"    },
  { name: "Cookie Clicker",            ...UGS("cookieclicker"),                            cat: "idle"        },
  { name: "Crazy Cars",                ...UGS("crazy cars"),                               cat: "racing"      },
  { name: "Crazy Chicken 3D",          ...UGS("crazy chicken 3D"),                         cat: "shooter"     },
  { name: "Creature Card Idle",        ...UGS("creature-card-idle"),                       cat: "idle"        },
  { name: "CS:GO Surf",                ...UGS("csgo surf"),                                cat: "action"      },
  { name: "Dandy's World Clicker",     ...UGS("dandys-world-clicker"),                     cat: "idle"        },
  { name: "D-Blox",                    ...UGS("dblox"),                                    cat: "puzzle"      },
  { name: "Deepest Sword",             ...UGS("deepest sword"),                            cat: "rpg"         },
  { name: "Demon Bluff",               ...UGS("demon-bluff"),                              cat: "horror"      },
  { name: "Die in the Dungeon",        ...UGS("die in the dungeon"),                       cat: "rpg"         },
  { name: "Dimension Incident",        ...UGS("dimension-incident"),                       cat: "horror"      },
  { name: "Doge Miner 2",              ...UGS("doge miner 2"),                             cat: "idle"        },
  { name: "Doodle Jump",               ...UGS("doodle jump"),                              cat: "platformer"  },
  { name: "Down the Mountain",         ...UGS("down the mountain"),                        cat: "action"      },
  { name: "Dragon",                    ...UGS("dragon"),                                   cat: "action"      },
  { name: "Drift Hunters",             ...UGS("drift-hunters"),                            cat: "racing"      },
  { name: "Drunken Duel",              ...UGS("drunken duel"),                             cat: "multiplayer" },
  { name: "Duck Life 6",               ...UGS("duck life 6"),                              cat: "rpg"         },
  { name: "Duck Life Battle",          ...UGS("duck life battle"),                         cat: "rpg"         },
  { name: "Dungeon Deck",              ...UGS("dungeondeck"),                              cat: "strategy"    },
  { name: "Eagle Ride",                ...UGS("eagle ride"),                               cat: "racing"      },
  { name: "Edy's Car Simulator",       ...UGS("edys car simulator"),                       cat: "racing"      },
  { name: "Eggy Car",                  ...UGS("eggy car"),                                 cat: "racing"      },
  { name: "Elastic Man",               ...UGS("elasticman"),                               cat: "other"       },
  { name: "Escalating Duel",           ...UGS("escalating-duel"),                          cat: "action"      },
  { name: "Escape Road 2",             ...UGS("escaperoad2city"),                          cat: "racing"      },

  // ── NERUVY GAMES (Neruvy/neruvy-games) ───────────────────────────────────
  { name: "1v1.LOL",                   ...NG("1v1lol"),                                    cat: "shooter"     },
  { name: "2048",                      ...NG("2048"),                                      cat: "puzzle"      },
  { name: "ARC",                       ...NG("ARC"),                                       cat: "action"      },
  { name: "Bob the Robber 2",          ...NG("bob-the-robber-2"),                          cat: "adventure"   },
  { name: "Drive Mad",                 ...NG("drive-mad"),                                 cat: "racing"      },
  { name: "Granny",                    ...NG("granny"),                                    cat: "horror"      },
  { name: "Moto X3M",                  ...NG("moto-x3m"),                                  cat: "racing"      },
  { name: "Moto X3M 2",                ...NG("motox3m2"),                                  cat: "racing"      },
  { name: "Poly Track",                ...NG("poly-track"),                                cat: "racing"      },
  { name: "Run 3",                     ...NG("run-3"),                                     cat: "platformer"  },
  { name: "Slope",                     ...NG("slope"),                                     cat: "action"      },
  { name: "Smash Karts",               ...NG("smash-karts"),                               cat: "racing"      },
  { name: "Snow Rider 3D",             ...NG("snow-rider"),                                cat: "racing"      },
  { name: "Survival Race",             ...NG("survival-race"),                             cat: "racing"      },
  { name: "Time Shooter 3: SWAT",      ...NG("time-shooter-3-swat"),                       cat: "shooter"     },
  { name: "Vex 3",                     ...NG("vex3"),                                      cat: "platformer"  },
  { name: "Vex 4",                     ...NG("vex4"),                                      cat: "platformer"  },
  { name: "Vex 5",                     ...NG("vex5"),                                      cat: "platformer"  },
  { name: "Vex 6",                     ...NG("vex6"),                                      cat: "platformer"  },
  { name: "Vex 7",                     ...NG("vex7"),                                      cat: "platformer"  },

  // ── WEB PORTS — Neruvy (Neruvy/web-port) ─────────────────────────────────
  { name: "Amanda the Adventurer",     ...NP("amanda-the-adventurer"),                     cat: "horror"      },
  { name: "Andy's Apple Farm",         ...NP("andys-apple-farm"),                          cat: "adventure"   },
  { name: "Baldi's Basics Plus",       ...NP("baldi-plus"),                                cat: "horror"      },
  { name: "Baldi's Basics Remastered", ...NP("baldi-remaster"),                            cat: "horror"      },
  { name: "Bendy and the Ink Machine", ...NP("bendy"),                                     cat: "horror"      },
  { name: "BERGENTRUCK",               ...NP("bergentruck"),                               cat: "adventure"   },
  { name: "BLOODMONEY!",               ...NP("bloodmoney"),                                cat: "action"      },
  { name: "Buckshot Roulette",         ...NP("buckshot-roulette"),                         cat: "horror"      },
  { name: "Class of '09",              ...NP("class-of-09"),                               cat: "adventure"   },
  { name: "Cuphead",                   ...NP("cuphead"),                                   cat: "action"      },
  { name: "Dead Plate",                ...NP("dead-plate"),                                cat: "horror"      },
  { name: "The Deadseat",              ...NP("deadseat"),                                  cat: "horror"      },
  { name: "Deltarune",                 ...NP("deltatraveler"),                             cat: "rpg"         },
  { name: "Do Not Take This Cat Home", ...NP("donottakethiscathome"),                      cat: "horror"      },
  { name: "Fears to Fathom",           ...NP("fears-to-fathom"),                           cat: "horror"      },
  { name: "Getting Over It",           ...NP("getting-over-it"),                           cat: "platformer"  },
  { name: "Happy Sheepies",            ...NP("happy-sheepies"),                            cat: "puzzle"      },
  { name: "Hotline Miami",             ...NP("hotline-miami"),                             cat: "action"      },
  { name: "Human Expenditure Program", ...NP("human-expenditure-program"),                 cat: "horror"      },
  { name: "Jelly Drift",               ...NP("jelly-drift"),                               cat: "racing"      },
  { name: "Karlson",                   ...NP("karlson"),                                   cat: "action"      },
  { name: "Kindergarten",              ...NP("kindergarten"),                              cat: "adventure"   },
  { name: "Lacy's Flash Games",        ...NP("lacysflashgames"),                           cat: "other"       },
  { name: "Milkman Karlson",           ...NP("milkman-karlson"),                           cat: "action"      },
  { name: "OMORI",                     ...NP("omori-fixed"),                               cat: "rpg"         },
  { name: "People Playground",         ...NP("people-playground"),                         cat: "other"       },
  { name: "Pizza Tower",               ...NP("pizza-tower"),                               cat: "platformer"  },
  { name: "Raft",                      ...NP("raft"),                                      cat: "adventure"   },
  { name: "Slender: The 8 Pages",      ...NP("slender"),                                   cat: "horror"      },
  { name: "Speed Stars",               ...NP("speed-stars"),                               cat: "racing"      },
  { name: "That's Not My Neighbor",    ...NP("thats-not-my-neighbor"),                     cat: "horror"      },
  { name: "The Man in the Window",     ...NP("the-man-in-the-window"),                     cat: "horror"      },
  { name: "ULTRAKILL",                 ...NP("ultrakill"),                                 cat: "action"      },
  { name: "Undertale Yellow",          ...NP("undertale-yellow"),                          cat: "rpg"         },
  { name: "WebFishing",                ...NP("web-fishing"),                               cat: "other"       },
  { name: "Yandere Simulator",         ...NP("yandere-simulator"),                         cat: "action"      },
  { name: "Yume Nikki",                ...NP("yume-nikki"),                                cat: "rpg"         },

  // ── WEB PORTS — Genizy exclusives (genizy/web-port) ──────────────────────
  { name: "Minesweeper Plus",          ...GP("minesweeperplus"),                           cat: "puzzle"      },
  { name: "Schoolboy Runaway",         ...GP("schoolboy-runaway"),                         cat: "action"      },
  { name: "Sonic.exe",                 ...GP("sonic.exe"),                                 cat: "horror"      },
  { name: "Tattletail",                ...GP("tattletail"),                                cat: "horror"      },
  { name: "Witch Heart",               ...GP("witch-heart"),                               cat: "rpg"         },

  // ── MATHTUT0R1NG (mathtut0r1ng.github.io) ────────────────────────────────
  { name: "A Dance of Fire and Ice",   ...MT("a-dance-of-fire-and-ice"),                   cat: "music"       },
  { name: "Amaze",                     ...MT("amaze"),                                     cat: "puzzle"      },
  { name: "Aquapark.io",               ...MT("aquapark.io"),                               cat: "sports"      },
  { name: "Basket Random",             ...MT("basket-random"),                             cat: "sports"      },
  { name: "Basketball Stars",          ...MT("basketball-stars"),                          cat: "sports"      },
  { name: "Block Blast",               ...MT("block-blast"),                               cat: "puzzle"      },
  { name: "Bouncemasters",             ...MT("bouncemasters"),                             cat: "action"      },
  { name: "Bowmasters",                ...MT("bowmasters"),                                cat: "action"      },
  { name: "Bridge Race",               ...MT("bridge-race"),                               cat: "racing"      },
  { name: "Clash Royale",              ...MT("clash"),                                     cat: "strategy"    },
  { name: "Crossy Road",               ...MT("crossy-road"),                               cat: "platformer"  },
  { name: "Eaglercraft 1.12.2",        ...MT("eaglercraft-1.12.2"),                        cat: "other"       },
  { name: "Five Nights at Freddy's",   ...MT("fnaf"),                                      cat: "horror"      },
  { name: "Five Nights at Freddy's 2", ...MT("fnaf2"),                                     cat: "horror"      },
  { name: "Five Nights at Freddy's 3", ...MT("fnaf3"),                                     cat: "horror"      },
  { name: "Five Nights at Freddy's 4", ...MT("fnaf4"),                                     cat: "horror"      },
  { name: "Friday Night Funkin'",      ...MT("friday-night-funkin"),                       cat: "music"       },
  { name: "Hill Climb Racing Lite",    ...MT("hill-climb-racing-lite"),                    cat: "racing"      },
  { name: "Hollow Knight",             ...MT("hollow-knight"),                             cat: "platformer"  },
  { name: "Paper.io 2",                ...MT("paper.io-2"),                                cat: "multiplayer" },
  { name: "Pixel Gun Survival",        ...MT("pixel-gun-survival"),                        cat: "shooter"     },
  { name: "R.E.P.O.",                  ...MT("repo"),                                      cat: "other"       },
  { name: "RE:RUN",                    ...MT("re-run"),                                    cat: "action"      },
  { name: "Slither.io",                ...MT("slither.io"),                                cat: "multiplayer" },
  { name: "Solar Smash",               ...MT("solar-smash"),                               cat: "other"       },
  { name: "Spiral Roll",               ...MT("spiral-roll"),                               cat: "puzzle"      },
  { name: "Sprunki",                   ...MT("sprunki"),                                   cat: "music"       },
  { name: "Super Mario 64",            ...MT("super-mario-64"),                            cat: "platformer"  },
  { name: "The Impossible Quiz",       ...MT("the-impossible-quiz"),                       cat: "puzzle"      },
  { name: "The World's Hardest Game",  ...MT("the-worlds-hardest-game"),                   cat: "platformer"  },
  { name: "They Are Coming",           ...MT("they-are-coming"),                           cat: "shooter"     },

];
