// URL helpers for each game source
const UGS = n => `https://bubbls.github.io/UGS-Assets/${encodeURIComponent(n)}/`;
const NG  = n => `https://neruvy.github.io/neruvy-games/games/${n}/`;
const NP  = n => `https://neruvy.github.io/web-port/${n}/`;
const GP  = n => `https://genizy.github.io/web-port/${n}/`;
const MT  = n => `https://mathtut0r1ng.github.io/gamespage/games/${n}/`;

const GAMES = [

  // ── UGS-ASSETS (bubbls.github.io/UGS-Assets) ─────────────────────────────
  { name: "1 Date Danger",              url: UGS("1-date-danger"),                            cat: "horror"      },
  { name: "10 Minutes Till Dawn",       url: UGS("10minutestilldawn"),                        cat: "shooter"     },
  { name: "2 Minute Football",          url: UGS("2 minute football"),                        cat: "sports"      },
  { name: "2-3-4 Player Games",         url: UGS("2-3-4-player-game"),                        cat: "multiplayer" },
  { name: "2 DOOM",                     url: UGS("2doom"),                                    cat: "action"      },
  { name: "3Dash",                      url: UGS("3dash"),                                    cat: "platformer"  },
  { name: "5B",                         url: UGS("5b"),                                       cat: "other"       },
  { name: "Antimatter Dimensions",      url: UGS("Antimatter Dimensions"),                    cat: "idle"        },
  { name: "Bumper Cars Soccer",         url: UGS("BUMPER CARS SOCCER"),                       cat: "sports"      },
  { name: "Blightborne",                url: UGS("Blightborne"),                              cat: "rpg"         },
  { name: "Burrito Bison",              url: UGS("BurritoBison-main"),                        cat: "action"      },
  { name: "Endacopia",                  url: UGS("Endacopia"),                                cat: "horror"      },
  { name: "Five Nights at Wario's",     url: UGS("FNAW-main"),                                cat: "horror"      },
  { name: "Five Nights at Osaka's",     url: UGS("Five Nights at Osaka's"),                   cat: "horror"      },
  { name: "Insomniary",                 url: UGS("Insomniary"),                               cat: "horror"      },
  { name: "Stickman GTA",               url: UGS("STICKMAN GTA"),                             cat: "action"      },
  { name: "Stickman Clash",             url: UGS("Stickman Clash"),                           cat: "action"      },
  { name: "A Day in the Office",        url: UGS("a day in the office"),                      cat: "other"       },
  { name: "Adventure Capitalist",       url: UGS("adventure-capitalist"),                     cat: "idle"        },
  { name: "Ages of Conflict",           url: UGS("ages of conflict"),                         cat: "strategy"    },
  { name: "Airline Tycoon Idle",        url: UGS("airline-tycoon-idle"),                      cat: "idle"        },
  { name: "Alien Sky Invasion",         url: UGS("alien sky invasion"),                       cat: "shooter"     },
  { name: "Amazing Rope Police",        url: UGS("amazing-strange-rope-police-vice-spider"),  cat: "action"      },
  { name: "Amidst the Sky",             url: UGS("amidst the sky"),                           cat: "platformer"  },
  { name: "Angry Birds",                url: UGS("angry-bird"),                               cat: "puzzle"      },
  { name: "Apes vs Helium",             url: UGS("apesvshelium"),                             cat: "action"      },
  { name: "Arcade Volley",              url: UGS("arcade-volley"),                            cat: "sports"      },
  { name: "Archesspalago",              url: UGS("archesspalago"),                            cat: "puzzle"      },
  { name: "Astro Survivors",            url: UGS("astro survivors"),                          cat: "shooter"     },
  { name: "Aviamaster",                 url: UGS("aviamaster"),                               cat: "strategy"    },
  { name: "Babel Tower",                url: UGS("babel tower"),                              cat: "puzzle"      },
  { name: "Backrooms 2D",               url: UGS("backrooms 2D"),                             cat: "horror"      },
  { name: "Bacon May Die",              url: UGS("bacon may die"),                            cat: "action"      },
  { name: "Bad Parenting",              url: UGS("bad-parenting"),                            cat: "platformer"  },
  { name: "Baldi's Basics",             url: UGS("baldis-basics"),                            cat: "horror"      },
  { name: "Baldi's Decomp",             url: UGS("baldi decomp"),                             cat: "horror"      },
  { name: "Ballistic",                  url: UGS("ballistic"),                                cat: "shooter"     },
  { name: "Banana Poker",               url: UGS("banana poker"),                             cat: "other"       },
  { name: "Barry Has a Secret",         url: UGS("barry has a secret"),                       cat: "horror"      },
  { name: "Baseball Bros",              url: UGS("baseball bros"),                            cat: "sports"      },
  { name: "Basket Stars",               url: UGS("basket stars"),                             cat: "sports"      },
  { name: "Basketball Superstars",      url: UGS("basketball-superstars"),                    cat: "sports"      },
  { name: "Beach Boxing Sim",           url: UGS("beach-boxing-sim"),                         cat: "sports"      },
  { name: "Bearsus",                    url: UGS("bearsus"),                                  cat: "action"      },
  { name: "Ben 10 Super Slammer",       url: UGS("ben 10 super slammer"),                     cat: "action"      },
  { name: "BFNSU",                      url: UGS("bfnsu"),                                    cat: "horror"      },
  { name: "Big 2048",                   url: UGS("big 2048"),                                 cat: "puzzle"      },
  { name: "Big Flappy Tower",           url: UGS("big flappy tower"),                         cat: "platformer"  },
  { name: "Block Miner",                url: UGS("block-miner"),                              cat: "idle"        },
  { name: "BlockPost",                  url: UGS("blockpost"),                                cat: "shooter"     },
  { name: "Blumgi Racers",              url: UGS("blumgi racers"),                            cat: "racing"      },
  { name: "Blumgi Rocket",              url: UGS("blumgi-rocket"),                            cat: "racing"      },
  { name: "Bounce Back",                url: UGS("bounce back"),                              cat: "puzzle"      },
  { name: "Bouncy Basketball",          url: UGS("bouncy basketball"),                        cat: "sports"      },
  { name: "Bouncy Motors",              url: UGS("bouncy motors"),                            cat: "racing"      },
  { name: "Bounty of One",              url: UGS("bounty of one"),                            cat: "rpg"         },
  { name: "Brawl 3D",                   url: UGS("brawl-3d"),                                 cat: "multiplayer" },
  { name: "Bullet Force",               url: UGS("bullet-force-multiplayer"),                 cat: "shooter"     },
  { name: "Capybara Clicker",           url: UGS("capybara clicker"),                         cat: "idle"        },
  { name: "Cat Mario",                  url: UGS("cat mario"),                                cat: "platformer"  },
  { name: "Cats Love Cake 2",           url: UGS("cats love cake 2"),                         cat: "puzzle"      },
  { name: "Cave Chaos 2",               url: UGS("cave chaos 2"),                             cat: "platformer"  },
  { name: "Cheese Chompers 3",          url: UGS("cheese chompers 3"),                        cat: "action"      },
  { name: "Chicken Gun",                url: UGS("chicken-gun"),                              cat: "shooter"     },
  { name: "Choppy Orc",                 url: UGS("choppy orc"),                               cat: "platformer"  },
  { name: "CircloO 2",                  url: UGS("circlo02"),                                 cat: "puzzle"      },
  { name: "Clash of Vikings",           url: UGS("clashofvikings"),                           cat: "strategy"    },
  { name: "Cookie Clicker",             url: UGS("cookieclicker"),                            cat: "idle"        },
  { name: "Crazy Cars",                 url: UGS("crazy cars"),                               cat: "racing"      },
  { name: "Crazy Chicken 3D",           url: UGS("crazy chicken 3D"),                         cat: "shooter"     },
  { name: "Creature Card Idle",         url: UGS("creature-card-idle"),                       cat: "idle"        },
  { name: "CS:GO Surf",                 url: UGS("csgo surf"),                                cat: "action"      },
  { name: "Dandy's World Clicker",      url: UGS("dandys-world-clicker"),                     cat: "idle"        },
  { name: "D-Blox",                     url: UGS("dblox"),                                    cat: "puzzle"      },
  { name: "Deepest Sword",              url: UGS("deepest sword"),                            cat: "rpg"         },
  { name: "Demon Bluff",                url: UGS("demon-bluff"),                              cat: "horror"      },
  { name: "Die in the Dungeon",         url: UGS("die in the dungeon"),                       cat: "rpg"         },
  { name: "Dimension Incident",         url: UGS("dimension-incident"),                       cat: "horror"      },
  { name: "Doge Miner 2",               url: UGS("doge miner 2"),                             cat: "idle"        },
  { name: "Doodle Jump",                url: UGS("doodle jump"),                              cat: "platformer"  },
  { name: "Down the Mountain",          url: UGS("down the mountain"),                        cat: "action"      },
  { name: "Dragon",                     url: UGS("dragon"),                                   cat: "action"      },
  { name: "Drift Hunters",              url: UGS("drift-hunters"),                            cat: "racing"      },
  { name: "Drunken Duel",               url: UGS("drunken duel"),                             cat: "multiplayer" },
  { name: "Duck Life 6",                url: UGS("duck life 6"),                              cat: "rpg"         },
  { name: "Duck Life Battle",           url: UGS("duck life battle"),                         cat: "rpg"         },
  { name: "Dungeon Deck",               url: UGS("dungeondeck"),                              cat: "strategy"    },
  { name: "Eagle Ride",                 url: UGS("eagle ride"),                               cat: "racing"      },
  { name: "Edy's Car Simulator",        url: UGS("edys car simulator"),                       cat: "racing"      },
  { name: "Eggy Car",                   url: UGS("eggy car"),                                 cat: "racing"      },
  { name: "Elastic Man",                url: UGS("elasticman"),                               cat: "other"       },
  { name: "Escalating Duel",            url: UGS("escalating-duel"),                          cat: "action"      },
  { name: "Escape Road 2",              url: UGS("escaperoad2city"),                          cat: "racing"      },

  // ── NERUVY GAMES (neruvy.github.io/neruvy-games/games) ───────────────────
  { name: "1v1.LOL",                    url: NG("1v1lol"),                                    cat: "shooter"     },
  { name: "2048",                       url: NG("2048"),                                      cat: "puzzle"      },
  { name: "ARC",                        url: NG("ARC"),                                       cat: "action"      },
  { name: "Bob the Robber 2",           url: NG("bob-the-robber-2"),                          cat: "adventure"   },
  { name: "Drive Mad",                  url: NG("drive-mad"),                                 cat: "racing"      },
  { name: "Granny",                     url: NG("granny"),                                    cat: "horror"      },
  { name: "Moto X3M",                   url: NG("moto-x3m"),                                  cat: "racing"      },
  { name: "Moto X3M 2",                 url: NG("motox3m2"),                                  cat: "racing"      },
  { name: "Poly Track",                 url: NG("poly-track"),                                cat: "racing"      },
  { name: "Retro Bowl",                 url: NG("retro-bowl"),                                cat: "sports"      },
  { name: "Run 3",                      url: NG("run-3"),                                     cat: "platformer"  },
  { name: "Slope",                      url: NG("slope"),                                     cat: "action"      },
  { name: "Smash Karts",                url: NG("smash-karts"),                               cat: "racing"      },
  { name: "Snow Rider 3D",              url: NG("snow-rider"),                                cat: "racing"      },
  { name: "Survival Race",              url: NG("survival-race"),                             cat: "racing"      },
  { name: "Time Shooter 3: SWAT",       url: NG("time-shooter-3-swat"),                       cat: "shooter"     },
  { name: "Vex 3",                      url: NG("vex3"),                                      cat: "platformer"  },
  { name: "Vex 4",                      url: NG("vex4"),                                      cat: "platformer"  },
  { name: "Vex 5",                      url: NG("vex5"),                                      cat: "platformer"  },
  { name: "Vex 6",                      url: NG("vex6"),                                      cat: "platformer"  },
  { name: "Vex 7",                      url: NG("vex7"),                                      cat: "platformer"  },

  // ── WEB PORTS — Neruvy (neruvy.github.io/web-port) ───────────────────────
  { name: "Amanda the Adventurer",      url: NP("amanda-the-adventurer"),                     cat: "horror"      },
  { name: "Andy's Apple Farm",          url: NP("andys-apple-farm"),                          cat: "adventure"   },
  { name: "Baldi's Basics Plus",        url: NP("baldi-plus"),                                cat: "horror"      },
  { name: "Baldi's Basics Remastered",  url: NP("baldi-remaster"),                            cat: "horror"      },
  { name: "Bendy and the Ink Machine",  url: NP("bendy"),                                     cat: "horror"      },
  { name: "BERGENTRUCK",                url: NP("bergentruck"),                               cat: "adventure"   },
  { name: "BLOODMONEY!",                url: NP("bloodmoney"),                                cat: "action"      },
  { name: "Buckshot Roulette",          url: NP("buckshot-roulette"),                         cat: "horror"      },
  { name: "Class of '09",               url: NP("class-of-09"),                               cat: "adventure"   },
  { name: "Cuphead",                    url: NP("cuphead"),                                   cat: "action"      },
  { name: "Dead Plate",                 url: NP("dead-plate"),                                cat: "horror"      },
  { name: "The Deadseat",               url: NP("deadseat"),                                  cat: "horror"      },
  { name: "Deltarune",                  url: NP("deltatraveler"),                             cat: "rpg"         },
  { name: "Do Not Take This Cat Home",  url: NP("donottakethiscathome"),                      cat: "horror"      },
  { name: "Fears to Fathom",            url: NP("fears-to-fathom"),                           cat: "horror"      },
  { name: "Getting Over It",            url: NP("getting-over-it"),                           cat: "platformer"  },
  { name: "Happy Sheepies",             url: NP("happy-sheepies"),                            cat: "puzzle"      },
  { name: "Hotline Miami",              url: NP("hotline-miami"),                             cat: "action"      },
  { name: "Human Expenditure Program",  url: NP("human-expenditure-program"),                 cat: "horror"      },
  { name: "Jelly Drift",                url: NP("jelly-drift"),                               cat: "racing"      },
  { name: "Karlson",                    url: NP("karlson"),                                   cat: "action"      },
  { name: "Kindergarten",               url: NP("kindergarten"),                              cat: "adventure"   },
  { name: "Lacy's Flash Games",         url: NP("lacysflashgames"),                           cat: "other"       },
  { name: "Milkman Karlson",            url: NP("milkman-karlson"),                           cat: "action"      },
  { name: "OMORI",                      url: NP("omori-fixed"),                               cat: "rpg"         },
  { name: "People Playground",          url: NP("people-playground"),                         cat: "other"       },
  { name: "Pizza Tower",                url: NP("pizza-tower"),                               cat: "platformer"  },
  { name: "Raft",                       url: NP("raft"),                                      cat: "adventure"   },
  { name: "Slender: The 8 Pages",       url: NP("slender"),                                   cat: "horror"      },
  { name: "Speed Stars",                url: NP("speed-stars"),                               cat: "racing"      },
  { name: "That's Not My Neighbor",     url: NP("thats-not-my-neighbor"),                     cat: "horror"      },
  { name: "The Man in the Window",      url: NP("the-man-in-the-window"),                     cat: "horror"      },
  { name: "ULTRAKILL",                  url: NP("ultrakill"),                                 cat: "action"      },
  { name: "Undertale Yellow",           url: NP("undertale-yellow"),                          cat: "rpg"         },
  { name: "WebFishing",                 url: NP("web-fishing"),                               cat: "other"       },
  { name: "Yandere Simulator",          url: NP("yandere-simulator"),                         cat: "action"      },
  { name: "Yume Nikki",                 url: NP("yume-nikki"),                                cat: "rpg"         },

  // ── WEB PORTS — Genizy exclusives (genizy.github.io/web-port) ────────────
  { name: "Minesweeper Plus",           url: GP("minesweeperplus"),                           cat: "puzzle"      },
  { name: "Schoolboy Runaway",          url: GP("schoolboy-runaway"),                         cat: "action"      },
  { name: "Sonic.exe",                  url: GP("sonic.exe"),                                 cat: "horror"      },
  { name: "Tattletail",                 url: GP("tattletail"),                                cat: "horror"      },
  { name: "Witch Heart",                url: GP("witch-heart"),                               cat: "rpg"         },

  // ── MATHTUT0R1NG (mathtut0r1ng.github.io/gamespage/games) ────────────────
  { name: "A Dance of Fire and Ice",    url: MT("a-dance-of-fire-and-ice"),                   cat: "music"       },
  { name: "Amaze",                      url: MT("amaze"),                                     cat: "puzzle"      },
  { name: "Aquapark.io",                url: MT("aquapark.io"),                               cat: "sports"      },
  { name: "Basket Random",              url: MT("basket-random"),                             cat: "sports"      },
  { name: "Basketball Stars",           url: MT("basketball-stars"),                          cat: "sports"      },
  { name: "Block Blast",                url: MT("block-blast"),                               cat: "puzzle"      },
  { name: "Bouncemasters",              url: MT("bouncemasters"),                             cat: "action"      },
  { name: "Bowmasters",                 url: MT("bowmasters"),                                cat: "action"      },
  { name: "Bridge Race",                url: MT("bridge-race"),                               cat: "racing"      },
  { name: "Clash Royale",               url: MT("clash"),                                     cat: "strategy"    },
  { name: "Crossy Road",                url: MT("crossy-road"),                               cat: "platformer"  },
  { name: "Eaglercraft 1.12.2",         url: MT("eaglercraft-1.12.2"),                        cat: "other"       },
  { name: "Five Nights at Freddy's",    url: MT("fnaf"),                                      cat: "horror"      },
  { name: "Five Nights at Freddy's 2",  url: MT("fnaf2"),                                     cat: "horror"      },
  { name: "Five Nights at Freddy's 3",  url: MT("fnaf3"),                                     cat: "horror"      },
  { name: "Five Nights at Freddy's 4",  url: MT("fnaf4"),                                     cat: "horror"      },
  { name: "Friday Night Funkin'",       url: MT("friday-night-funkin"),                       cat: "music"       },
  { name: "Hill Climb Racing Lite",     url: MT("hill-climb-racing-lite"),                    cat: "racing"      },
  { name: "Hollow Knight",              url: MT("hollow-knight"),                             cat: "platformer"  },
  { name: "Paper.io 2",                 url: MT("paper.io-2"),                                cat: "multiplayer" },
  { name: "Pixel Gun Survival",         url: MT("pixel-gun-survival"),                        cat: "shooter"     },
  { name: "R.E.P.O.",                   url: MT("repo"),                                      cat: "other"       },
  { name: "RE:RUN",                     url: MT("re-run"),                                    cat: "action"      },
  { name: "Slither.io",                 url: MT("slither.io"),                                cat: "multiplayer" },
  { name: "Solar Smash",                url: MT("solar-smash"),                               cat: "other"       },
  { name: "Spiral Roll",                url: MT("spiral-roll"),                               cat: "puzzle"      },
  { name: "Sprunki",                    url: MT("sprunki"),                                   cat: "music"       },
  { name: "Super Mario 64",             url: MT("super-mario-64"),                            cat: "platformer"  },
  { name: "The Impossible Quiz",        url: MT("the-impossible-quiz"),                       cat: "puzzle"      },
  { name: "The World's Hardest Game",   url: MT("the-worlds-hardest-game"),                   cat: "platformer"  },
  { name: "They Are Coming",            url: MT("they-are-coming"),                           cat: "shooter"     },

];
